      common/lj0001/numlj
      common/lj0002/amasslj,recamasslj,hmasslj
      common/lj0003/polarlj,xk1lj
      common/lj0004/qmasschglj,qmasschgreclj
      common/lj0005/chrgrelaxlj,chrgrelaxsqlj,chrgrelaxsqreclj
c      common/lj0006/epsilon(nspmax),sigma(nspmax)
      common/lj0007/chrgtkblj,gchglj,gchgreclj,gchgtimlj,gchgkinlj
      common/lj0008/dmsdlj
      common/lj0009/frrxlj(nummax)
     x             ,frrylj(nummax)
     x             ,frrzlj(nummax)
      common/lj0010/xlj(nummax)
     x             ,ylj(nummax)
     x             ,zlj(nummax)
      common/lj0011/vxlj(nummax)
     x             ,vylj(nummax)
     x             ,vzlj(nummax)
      common/lj0012/vxnlj(nummax)
     x             ,vynlj(nummax)
     x             ,vznlj(nummax)
      common/lj0013/rxnlj(nummax)
     x             ,rynlj(nummax)
     x             ,rznlj(nummax)
      common/lj0014/dtzeta2lj,zetanewlj,zetalj
      common/lj0015/trankelj,xkesqlj,tkelj
      common/lj0016/dtchrgzeta2lj,chrgzetanewlj,chrgzetalj
      common/lj0017/xmulj(nummax)
     x             ,ymulj(nummax)
     x             ,zmulj(nummax)
      common/lj0018/xmunlj(nummax)
     x             ,ymunlj(nummax)
     x             ,zmunlj(nummax)
      common/lj0010/qvelxlj(nummax)
     x             ,qvelylj(nummax)
     x             ,qvelzlj(nummax)
      common/lj0020/qvelnxlj(nummax)
     x             ,qvelnylj(nummax)
     x             ,qvelnzlj(nummax)
      common/lj0021/englj,engljion,engljionsr,engljdipdip
     x             ,engljchg,engpetotlj
      common/lj0022/gtranlj,gtranreclj,gtrantimlj,gtrankinlj
      common/lj0023/tkinlj
      common/lj0024/rstinlj
      common/lj0025/elecxlj(nummax)
     x             ,elecylj(nummax)
     x             ,eleczlj(nummax)
      common/lj0026/fkelj,resenglj


      common/lj0027/ljsubsystem
      logical ljsubsystem

c      common/lj0028/fadeljpotlog,xlambdalj,nstepfadelj
     x             ,deltalambdalj
      logical fadeljpotlog
